# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the python-dateutil library that can be
# found from pypi.
# timezone =

# max length of characters to apply to the
# "revision" field
rev_id = sha

# If set, 'alembic history' will assume an implicit cycled base
# revision at the beginning of the history stream.
# cyclic_base_data =

# If set, 'alembic history' will assume an implicit cycled base
# revision at the end of the history stream.
# cyclic_head_data =

# The encoding used when reading/writing files
# Default: utf-8
# file_encoding =

# The output buffer size when revising
# Defaults to stdout buffering
# output_buffer =

# When False, the emitted SQL will include the literal per-database
# parameters that SQLA uses to talk to the DB.
# This overrides the sqlalchemy.url setting
# for offline mode
# sqlalchemy.url = driver://user:pass@localhost/dbname

sqlalchemy.url =postgresql://neondb_owner:npg_p6wSvbRYHm7o@ep-quiet-base-b31ob5zk-pooler.c-4.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
