lines = [
    "import sys",
    "import os",
    "sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))",
    "import pytest",
    "from sqlalchemy.ext.asyncio import AsyncSession",
    "from app.db.models import User, RoadSegment",
    "from app.db.models.incident import IncidentStatus",
    "from app.schemas.segment import SegmentStatusUpdate",
    "from app.db.session import get_db",
    "from app.core.security import get_current_user_with_role",
    "",
    "@pytest.mark.asyncio",
    "async def test_update_segment_status_success(db_session: AsyncSession):",
    "    # Create a user with ADMIN role",
    "    user = User(",
    "        id=1,",
    "        username=\"admin\",",
    "        email=\"admin@example.com\",",
    "        password_hash=\"hashed\",",
    "        role=\"ADMIN\",",
    "        is_active=True",
    "    )",
    "    db_session.add(user)",
    "    await db_session.commit()",
    "",
    "    # Create a road segment",
    "    segment = RoadSegment(",
    "        id=1,",
    "        start_node_id=1,",
    "        end_node_id=2,",
    "        status=\"UNKNOWN\"",
    "    )",
    "    db_session.add(segment)",
    "    await db_session.commit()",
    "",
    "    # Import the app and override dependencies",
    "    from app.main import app",
    "    from fastapi.testclient import TestClient",
    "",
    "    # Override the get_db dependency",
    "    async def override_get_db():",
    "        yield db_session",
    "",
    "    app.dependency_overrides[get_db] = override_get_db",
    "",
    "    # Override the get_current_user_with_role dependency to return our user",
    "    async def override_get_current_user_with_role(token: str, db: AsyncSession):",
    "        return user",
    "",
    "    app.dependency_overrides[get_current_user_with_role] = override_get_current_user_with_role",
    "",
    "    with TestClient(app) as client:",
    "        response = client.patch(",
    "            \"/api/v1/roads/segments/1/status\",",
    "            json={\"status\": \"BLOCKED\", \"reason\": \"Test reason\"}",
    "        )",
    "        assert response.status_code == 200",
    "        data = response.json()",
    "        assert data[\"status\"] == \"BLOCKED\"",
    "        assert data[\"id\"] == 1",
    "",
    "    # Check that the segment status was updated in the database",
    "    from sqlalchemy import select",
    "    result = await db_session.execute(select(RoadSegment.status).where(RoadSegment.id == 1))",
    "    current_status = result.scalar_one()",
    "    assert current_status == \"BLOCKED\"",
    "",
    "    # Check that an audit log was created",
    "    from app.db.models import AuditLog",
    "    result = await db_session.execute(",
    "        select(AuditLog).where(AuditLog.table_name == \"road_segments\", AuditLog.record_id == 1)",
    "    )",
    "    audit_log = result.scalar_one_or_none()",
    "    assert audit_log is not None",
    "    assert audit_log.user_id == user.id",
    "    assert audit_log.action == \"MANUALLY_UPDATE_ROAD_STATUS\"",
    "    assert \"Changed status from UNKNOWN to BLOCKED\" in audit_log.changes",
    "    assert audit_log.ip_address is None",
    "",
    "    # Clean up overrides",
    "    app.dependency_overrides.clear()",
    "",
    "@pytest.mark.asyncio",
    "async def test_update_segment_status_unauthorized(db_session: AsyncSession):",
    "    # Create a user with DRIVER role (not allowed)",
    "    user = User(",
    "        id=1,",
    "        username=\"driver\",",
    "        email=\"driver@example.com\",",
    "        password_hash=\"hashed\",",
    "        role=\"DRIVER\",",
    "        is_active=True",
    "    )",
    "    db_session.add(user)",
    "    await db_session.commit()",
    "",
    "    # Create a road segment",
    "    segment = RoadSegment(",
    "        id=1,",
    "        start_node_id=1,",
    "        end_node_id=2,",
    "        status=\"UNKNOWN\"",
    "    )",
    "    db_session.add(segment)",
    "    await db_session.commit()",
    "",
    "    # Import the app and override dependencies",
    "    from app.main import app",
    "    from fastapi.testclient import TestClient",
    "",
    "    # Override the get_db dependency",
    "    async def override_get_db():",
    "        yield db_session",
    "",
    "    app.dependency_overrides[get_db] = override_get_db",
    "",
    "    # Override the get_current_user_with_role dependency to return our user",
    "    async def override_get_current_user_with_role(token: str, db: AsyncSession):",
    "        return user",
    "",
    "    app.dependency_overrides[get_current_user_with_role] = override_get_current_user_with_role",
    "",
    "    with TestClient(app) as client:",
    "        response = client.patch(",
    "            \"/api/v1/roads/segments/1/status\",",
    "            json={\"status\": \"BLOCKED\", \"reason\": \"Test reason\"}",
    "        )",
    "        # Should be forbidden",
    "        assert response.status_code == 403",
    "",
    "    # Clean up overrides",
    "    app.dependency_overrides.clear()",
    "",
    "@pytest.mark.asyncio",
    "async def test_update_segment_status_invalid_status(db_session: AsyncSession):",
    "    # Create a user with ADMIN role",
    "    user = User(",
    "        id=1,",
    "        username=\"admin\",",
    "        email=\"admin@example.com\",",
    "        password_hash=\"hashed\",",
    "        role=\"ADMIN\",",
    "        is_active=True",
    "    )",
    "    db_session.add(user)",
    "    await db_session.commit()",
    "",
    "    # Create a road segment",
    "    segment = RoadSegment(",
    "        id=1,",
    "        start_node_id=1,",
    "        end_node_id=2,",
    "        status=\"UNKNOWN\"",
    "    )",
    "    db_session.add(segment)",
    "    await db_session.commit()",
    "",
    "    # Import the app and override dependencies",
    "    from app.main import app",
    "    from fastapi.testclient import TestClient",
    "",
    "    # Override the get_db dependency",
    "    async def override_get_db():",
    "        yield db_session",
    "",
    "    app.dependency_overrides[get_db] = override_get_db",
    "",
    "    # Override the get_current_user_with_role dependency to return our user",
    "    async def override_get_current_user_with_role(token: str, db: AsyncSession):",
    "        return user",
    "",
    "    app.dependency_overrides[get_current_user_with_role] = override_get_current_user_with_role",
    "",
    "    with TestClient(app) as client:",
    "        response = client.patch(",
    "            \"/api/v1/roads/segments/1/status\",",
    "            json={\"status\": \"INVALID\", \"reason\": \"Test reason\"}",
    "        )",
    "        # Should be bad request",
    "        assert response.status_code == 400",
    "",
    "    # Clean up overrides",
    "    app.dependency_overrides.clear()",
]

with open('./tests/test_roads.py', 'w') as f:
    f.write('\n'.join(lines))
